create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  phone_number text not null unique,
  full_name text,
  preferred_language text not null default 'EN',
  onboarding_step text not null default 'AWAITING_LANGUAGE',
  has_niu boolean,
  niu_value text,
  business_name text,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists preferred_language text not null default 'EN';
alter table public.profiles add column if not exists has_niu boolean;
alter table public.profiles add column if not exists niu_value text;
alter table public.profiles add column if not exists business_name text;
alter table public.profiles add column if not exists last_message_at timestamptz;

create table if not exists public.whatsapp_events (
  id bigint generated by default as identity primary key,
  whatsapp_message_id text not null unique,
  phone_number text not null,
  created_at timestamptz not null default now()
);

drop table if exists public.ledger_entries;

do $$
declare
  profiles_id_udt text;
begin
  select c.udt_name
    into profiles_id_udt
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'profiles'
    and c.column_name = 'id';

  if profiles_id_udt = 'uuid' then
    execute $sql$
      create table public.ledger_entries (
        id bigint generated by default as identity primary key,
        profile_id uuid references public.profiles(id) on delete cascade,
        entry_type text not null check (entry_type in ('INCOME', 'EXPENSE')),
        amount_cfa numeric(14,2) not null check (amount_cfa > 0),
        source_text text,
        created_at timestamptz not null default now()
      )
    $sql$;
  elsif profiles_id_udt = 'int8' then
    execute $sql$
      create table public.ledger_entries (
        id bigint generated by default as identity primary key,
        profile_id bigint references public.profiles(id) on delete cascade,
        entry_type text not null check (entry_type in ('INCOME', 'EXPENSE')),
        amount_cfa numeric(14,2) not null check (amount_cfa > 0),
        source_text text,
        created_at timestamptz not null default now()
      )
    $sql$;
  else
    raise exception 'Unsupported profiles.id type: %', profiles_id_udt;
  end if;
end $$;

create index if not exists idx_ledger_entries_profile_id on public.ledger_entries(profile_id);
create index if not exists idx_ledger_entries_created_at on public.ledger_entries(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();
